### ISSUE TITLE
Booting from read-only medium throws "DEVICE ERROR D-002"

### ISSUE THREAD

**Issue by strfry** [zoff99/ToxBlinkenwall_image_usb_portable#1]
Testing the boot image in a VM required me to mount it as a DVD image.
In this case, the luks script won't setup the persistent encrypted partition.

Maybe there should be an option to drop this step and just use ephemeral keys on a tmpfs.
This might also be useful for testing.

**Comment by zoff99** [comment]
what VM did you use?

**Comment by strfry** [comment]
First seen in Hyper-V.
Also occurs in bhyve, when i set disk0_type to "ahci-cd".

**Comment by strfry** [comment]
Since a37284f5f5206f8a0d1373eb3e3fd991b11674fa , it displays "DEVICE ERROR D-004" instead, but continues after 10 seconds in non-persistent mode. This seems much better.

Regarding those cryptic error numbers, they should be documented on the manual somewhere. Note to myself to start working on documentation ;)
